name: generate animation

on: 
  schedule:
    # run automatically every 24 hours
    - cron: '0 */24 * * *'

    # allows to manually run the workflow at any time
    workflow_dispatch:

    # run on every push on the master branch 
    push:
      branches:
        - master
  
jobs:
  generate:
    permission:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph,
      # output a svg animation at <svg_output_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: | 
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.png?pallet=dark

      # push the content of <build_dir> to a branch
      # the content will be available at  https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contributions-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}